version: "3"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: hyperjump-web-framework
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - 9000:9000 # web interface. Open http://localhost:9000 to view the inbox.
      - 2500:2500 # SMTP server. Use this to send emails.
      - 1100:1100 # POP3 server
    restart: unless-stopped
